{% set data = load_setup_py_data() %}


package:
  name: "hellopythonworld"
  version: "{{ data['version'] }}"

source:
  path: ..

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - hellopythonworld

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
  summary: {{ data['description'] }}
